setwd("C:\\Users\\tanveer.khan\\Desktop\\Data Science\\exdata-data-NEI_data")
getwd()
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
str(NEI)
NEI <- transform(NEI,year=as.factor(year))
str(NEI)
names(NEI)
names(SCC)
s <- split(Emissions,year,drop=T)
v1 <- sapply(s,sum)
plot(names(v1),v1,type="l",xlim=c(1999,2008),xlab="Year",ylab="Total Emissions",col="red",main="Total Emission/Year")